### ISSUE TITLE
Large JSON request crashing application

### ISSUE THREAD

**Issue by jbodah** [parroty/http_server#10]
I have a complex JSON body being POST'ed to an HttpServer which is crashing in the handler [here](https://github.com/parroty/http_server/blob/master/lib/http_server/handler.ex#L122) because a query string is trying to be parsed from the body. I would suggest instead only doing this if the content type is `application/x-www-form-urlencoded`

**Comment by jbodah** [comment]
@parroty any chance you might be able to take a peek at this?

**Comment by parroty** [comment]
Thanks, just merged (sorry being late).
